# Generated by Django 5.0.14 on 2026-07-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=11)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField()),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick')], default='annual', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr_payroll.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sgk_employee_premium', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unemployment_employee_premium', models.DecimalField(decimal_places=2, max_digits=14)),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stamp_duty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('employer_sgk_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('employer_unemployment_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr_payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr_payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__last_name'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
