# Generated by Django 5.0.14 on 2026-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bill_invoice_party_billline_invoiceline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(default='adet', max_length=20)),
                ('cost_method', models.CharField(choices=[('fifo', 'FIFO'), ('weighted_average', 'Weighted Average')], default='weighted_average', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
