# Generated by Django 5.0.14 on 2026-08-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['screen_key', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('screen_key', 'owner', 'name'), name='unique_saved_view_name_per_owner_screen'),
        ),
    ]
