from django.db import transaction
from django.db.models import F, Sum
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.core.permissions import HasActivePackage

from .models import StockMove, Warehouse
from .serializers import (
    StockLevelRowSerializer,
    StockMoveSerializer,
    TransferSerializer,
    WarehouseSerializer,
)


class WarehouseViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated, HasActivePackage("inventory")]
    queryset = Warehouse.objects.all()
    serializer_class = WarehouseSerializer


class StockMoveViewSet(viewsets.ModelViewSet):
    """
    Manual stock movements (REQ-INV-002/003) -- receipts generated by
    Purchasing's receive action (apps/purchasing/views.py) create these rows
    directly via the model, not through this endpoint; this is for
    adjustments and the transfer action a warehouse user triggers by hand.
    """

    permission_classes = [IsAuthenticated, HasActivePackage("inventory")]
    queryset = StockMove.objects.select_related("item", "warehouse").all()
    serializer_class = StockMoveSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["item", "warehouse", "move_type"]

    @action(detail=False, methods=["post"])
    def transfer(self, request):
        serializer = TransferSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        with transaction.atomic():
            StockMove.objects.create(
                item=data["item"],
                warehouse=data["from_warehouse"],
                move_type=StockMove.TRANSFER_OUT,
                quantity=-data["quantity"],
                reference=data["reference"],
            )
            StockMove.objects.create(
                item=data["item"],
                warehouse=data["to_warehouse"],
                move_type=StockMove.TRANSFER_IN,
                quantity=data["quantity"],
                reference=data["reference"],
            )
        return Response({"detail": "Transfer completed."})


class StockLevelView(APIView):
    """
    REQ-INV-001/002: current stock-on-hand per item/warehouse. A single-table
    Sum() aggregation is safe here (see StockMove's docstring for why this
    differs from FinancialDocument's Python-computed totals) -- but the
    result is still routed through an explicit serializer, not a raw dict, to
    keep the same "never a bare float for a quantity/amount" discipline.
    """

    permission_classes = [IsAuthenticated, HasActivePackage("inventory")]

    def get(self, request):
        rows = (
            StockMove.objects.values(
                item_sku=F("item__sku"),
                item_name=F("item__name"),
                warehouse_code=F("warehouse__code"),
                warehouse_name=F("warehouse__name"),
            )
            .annotate(quantity_on_hand=Sum("quantity"))
            .order_by("item_sku", "warehouse_code")
        )
        rows = [r for r in rows if r["quantity_on_hand"] != 0]
        return Response(StockLevelRowSerializer(rows, many=True).data)
