# Generated by Django 5.0.14 on 2026-08-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_backfill_default_entity'),
        ('inventory', '0001_initial'),
        ('sales_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('trendyol', 'Trendyol'), ('hepsiburada', 'Hepsiburada')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('shop_domain', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_accounts', to='core.entity')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_accounts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sku', models.CharField(max_length=100)),
                ('external_variant_id', models.CharField(blank=True, max_length=100)),
                ('external_location_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='ecommerce.marketplaceaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='core.item')),
            ],
            options={
                'ordering': ['account', 'external_sku'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('synced', 'Synced'), ('failed', 'Failed')], default='new', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ecommerce.marketplaceaccount')),
                ('sales_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_order', to='sales_crm.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketplacelisting',
            constraint=models.UniqueConstraint(fields=('account', 'item'), name='unique_listing_per_account_item'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceorder',
            constraint=models.UniqueConstraint(fields=('account', 'external_order_id'), name='unique_external_order_per_account'),
        ),
    ]
